# Generated by Django 2.1.15 on 2020-08-05 13:31

from django.db import migrations
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        ('taggit', '0003_taggeditem_add_unique_index'),
        ('images', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='images',
            name='downloads',
        ),
        migrations.RemoveField(
            model_name='images',
            name='likes',
        ),
        migrations.RemoveField(
            model_name='images',
            name='tags',
        ),
        migrations.AddField(
            model_name='images',
            name='tags',
            field=taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags'),
        ),
    ]
