# Generated by Django 2.1.15 on 2020-08-06 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0003_images_pic_day'),
    ]

    operations = [
        migrations.AlterField(
            model_name='images',
            name='pic_day',
            field=models.BooleanField(default=False),
        ),
    ]
