# Generated by Django 2.1.15 on 2020-08-07 13:42

from django.db import migrations, models
import images.models


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0004_auto_20200806_1245'),
    ]

    operations = [
        migrations.AddField(
            model_name='images',
            name='desktop',
            field=models.ImageField(blank=True, default='default.jpg', upload_to=images.models.reference_main_image_path),
        ),
    ]
